Add test report

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -32,6 +32,13 @@ jobs:
           ${{ runner.os }}-maven-
     - name: Verify
       run: mvn -B clean verify -pl plantuml-web -am -Dgroups="smoke"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JUnit Tests            # Name of the check run which will be created
+        path: '*/target/surefire-reports/TEST-*.xml'    # Path to test results
+        reporter: jest-junit        # Format of test results
 
   deployment:
     runs-on: ubuntu-latest
@@ -61,3 +68,10 @@ jobs:
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
       - name: Deploy
         run: mvn -B clean deploy
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JUnit Tests            # Name of the check run which will be created
+          path: '*/target/surefire-reports/TEST-*.xml'    # Path to test results
+          reporter: jest-junit        # Format of test results
